import { ApifyClient } from 'apify-client'
import { ApifyTwitterRes } from './types'

// Initialize the ApifyClient with API token
const apikeys = [
    { token: 'apify_api_hGr4XrNcBxsY5mLd2kluTCr8TW8GAA3NdFbI', client: 'inalienable_pony/twitter-scraper-task' },
    { token: 'apify_api_kkOyeZBCaxZIQL89Odagqmw55O98io0GOs00', client: 'guiltless_shrub/twitter-scraper' },
]

const activeAccount = 0

const client = new ApifyClient({
    token: apikeys[activeAccount].token,
})

export const scrapeProfile = async (twitterProfileName: string): Promise<ApifyTwitterRes[]> => {
    const task = client.task(apikeys[activeAccount].client)

    const run = await task.call({
        addUserInfo: false,
        collectOriginalTweetOnly: true,
        debugLog: false,
        handles: [twitterProfileName],
        includeThreadsOnly: false,
        initialCookies: [
            {
                domain: '.twitter.com',
                expirationDate: 1707563750.808061,
                hostOnly: false,
                httpOnly: false,
                name: 'eu_cn',
                path: '/',
                sameSite: null,
                secure: true,
                session: false,
                storeId: null,
                value: '1',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1715225300,
                hostOnly: false,
                httpOnly: false,
                name: 'des_opt_in',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'Y',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1720693840.487519,
                hostOnly: false,
                httpOnly: false,
                name: '_ga_ZJQNEMXF73',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'GS1.1.1686133839.1.0.1686133840.0.0.0',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725443576.544815,
                hostOnly: false,
                httpOnly: false,
                name: 'mbox',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'PC#9b89ded1d9d84d62bb0233306d99d69a.38_0#1754128377|session#62c4ce2b8c57430ca2107ed826951a13#1690885437',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612530.236376,
                hostOnly: false,
                httpOnly: false,
                name: 'dnt',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: '1',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612530.471273,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: 'v1%3A169105253036479485',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1693909839,
                hostOnly: false,
                httpOnly: false,
                name: '_gac_UA-30775-92',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: '1.1686133839.CjwKCAjw1YCkBhAOEiwA5aN4AV0zW8wZQw-KYVnWNp1-U9VUiDNLJbWI0iFJ0RSXV3q24qRZBIqvDhoCVJQQAvD_BwE',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612721.791226,
                hostOnly: false,
                httpOnly: false,
                name: '_ga',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'GA1.2.1060841582.1688970019',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725443589.919333,
                hostOnly: false,
                httpOnly: false,
                name: '_ga_BYKEBDM7DS',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'GS1.1.1690883577.9.0.1690883589.0.0.0',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721200082.597108,
                hostOnly: false,
                httpOnly: false,
                name: '_ga_J2XYV9CGE1',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'GS1.1.1686640078.1.0.1686640082.0.0.0',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1693909839,
                hostOnly: false,
                httpOnly: false,
                name: '_gac_UA-30775-61',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: '1.1686133839.CjwKCAjw1YCkBhAOEiwA5aN4AV0zW8wZQw-KYVnWNp1-U9VUiDNLJbWI0iFJ0RSXV3q24qRZBIqvDhoCVJQQAvD_BwE',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1691465301,
                hostOnly: false,
                httpOnly: false,
                name: '_gcl_au',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: '1.1.1456504170.1683689301',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1691139121,
                hostOnly: false,
                httpOnly: false,
                name: '_gid',
                path: '/',
                sameSite: null,
                secure: false,
                session: false,
                storeId: null,
                value: 'GA1.2.1758870813.1690705287',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612530.2364,
                hostOnly: false,
                httpOnly: false,
                name: 'ads_prefs',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: '"HBESAAA="',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612722.012348,
                hostOnly: false,
                httpOnly: true,
                name: 'auth_multi',
                path: '/',
                sameSite: 'lax',
                secure: true,
                session: false,
                storeId: null,
                value: '"1414410300778893312:24f4e61724d5f2460b65d8f5964b8da52cc3a5e8"',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612530.236548,
                hostOnly: false,
                httpOnly: true,
                name: 'auth_token',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: '43fcf37a871ab24261636e1c790a2673ad372cd7',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612530.471282,
                hostOnly: false,
                httpOnly: false,
                name: 'ct0',
                path: '/',
                sameSite: 'lax',
                secure: true,
                session: false,
                storeId: null,
                value: 'f90b62eb6f48424b500126fbdd63c15a817f3737760849de19800b8f7525e2c61278fb6d081abfbd556a3ac2b539da5f74a1892b179e33d744989723270de5913f645045b6cacc1ac22f033aeaf5e785',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1697268320.173266,
                hostOnly: false,
                httpOnly: false,
                name: 'd_prefs',
                path: '/',
                sameSite: null,
                secure: true,
                session: false,
                storeId: null,
                value: 'MToxLGNvbnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612724.28978,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id_ads',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: 'v1%3A169105253036479485',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612724.289815,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id_marketing',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: 'v1%3A169105253036479485',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1723530348.163607,
                hostOnly: false,
                httpOnly: true,
                name: 'kdt',
                path: '/',
                sameSite: null,
                secure: true,
                session: false,
                storeId: null,
                value: 'OTudKopzh6yoy4X6g0LmrgUsShDFGa4ptiuHUZhu',
            },
            {
                domain: 'twitter.com',
                hostOnly: true,
                httpOnly: false,
                name: 'lang',
                path: '/',
                sameSite: null,
                secure: false,
                session: true,
                storeId: null,
                value: 'en',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1725612724.289836,
                hostOnly: false,
                httpOnly: false,
                name: 'personalization_id',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: '"v1_+nj+smPhQH4z+TRGURiTGg=="',
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722588724.289846,
                hostOnly: false,
                httpOnly: false,
                name: 'twid',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: null,
                value: 'u%3D1651534847754797056',
            },
        ],
        mode: 'own',
        profilesDesired: 1,
        proxyConfig: {
            useApifyProxy: true,
        },
        repliesDepth: 1,
        searchMode: 'live',
        skipRetweets: true,
        tweetsDesired: 2,
        useAdvancedSearch: false,
    })

    const { items }: any = await client.dataset(run.defaultDatasetId).listItems()

    return items
}
