import { ApifyClient } from 'apify-client'
import { ApifyTwitterRes } from './types'

// Initialize the ApifyClient with API token
const apikeys = [
    { token: 'apify_api_hGr4XrNcBxsY5mLd2kluTCr8TW8GAA3NdFbI', client: 'inalienable_pony/twitter-scraper-task' },
    { token: 'apify_api_kkOyeZBCaxZIQL89Odagqmw55O98io0GOs00', client: 'guiltless_shrub/twitter-scraper' },
]

const activeAccount = 0

const client = new ApifyClient({
    token: apikeys[activeAccount].token,
})

export const scrapeProfile = async (twitterProfileName: string): Promise<ApifyTwitterRes[]> => {
    const task = client.task(apikeys[activeAccount].client)

    const run = await task.call({
        addUserInfo: false,
        collectOriginalTweetOnly: true,
        debugLog: false,
        handles: [twitterProfileName],
        includeThreadsOnly: false,
        initialCookies: [
            {
                domain: '.twitter.com',
                expirationDate: 1722700980.278229,
                hostOnly: false,
                httpOnly: false,
                name: '_ga',
                path: '/',
                sameSite: 'unspecified',
                secure: false,
                session: false,
                storeId: '0',
                value: 'GA1.2.1521572653.1686805660',
                id: 1,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1688227380,
                hostOnly: false,
                httpOnly: false,
                name: '_gid',
                path: '/',
                sameSite: 'unspecified',
                secure: false,
                session: false,
                storeId: '0',
                value: 'GA1.2.515713126.1688050347',
                id: 2,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721375575.384115,
                hostOnly: false,
                httpOnly: false,
                name: 'ads_prefs',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: '"HBISAAA="',
                id: 3,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722700980.469732,
                hostOnly: false,
                httpOnly: true,
                name: 'auth_multi',
                path: '/',
                sameSite: 'lax',
                secure: true,
                session: false,
                storeId: '0',
                value: '"922505804200194048:a11e320be45a50d8c01d8e6c945d3c9cb577526e"',
                id: 4,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721375575.384174,
                hostOnly: false,
                httpOnly: true,
                name: 'auth_token',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: 'ea5c097378074445db08bc889271fc243c265be6',
                id: 5,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721375575.577445,
                hostOnly: false,
                httpOnly: false,
                name: 'ct0',
                path: '/',
                sameSite: 'lax',
                secure: true,
                session: false,
                storeId: '0',
                value: '03eb8bada3a97cd3fd83fe1fc995030aebcb112755b0c2a00d43f63c22fb3e709d44468c7a8183cd8bd8790bd6f4a81ca494093f98d64b663adf1e24a9c08e42557887986e071c3f3fc09f3038818c22',
                id: 6,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1702357652.533784,
                hostOnly: false,
                httpOnly: false,
                name: 'd_prefs',
                path: '/',
                sameSite: 'unspecified',
                secure: true,
                session: false,
                storeId: '0',
                value: 'MToxLGNvbnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw',
                id: 7,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722449512.212042,
                hostOnly: false,
                httpOnly: false,
                name: 'dnt',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: '1',
                id: 8,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1688745780.29925,
                hostOnly: false,
                httpOnly: false,
                name: 'external_referer',
                path: '/',
                sameSite: 'unspecified',
                secure: true,
                session: false,
                storeId: '0',
                value: 'padhuUp37zjgzgv1mFWxJ12Ozwit7owX|0|ziZgIoZIK4nlMKUVLq9KcnBFms0d9TqBqrE%2FyjvSFlFJR45yIlYF%2Bw%3D%3D',
                id: 9,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721375575.577438,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: 'v1%3A168681557544160836',
                id: 10,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722700984.166978,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id_ads',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: 'v1%3A168681557544160836',
                id: 11,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722700984.167025,
                hostOnly: false,
                httpOnly: false,
                name: 'guest_id_marketing',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: 'v1%3A168681557544160836',
                id: 12,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1721021204.418165,
                hostOnly: false,
                httpOnly: true,
                name: 'kdt',
                path: '/',
                sameSite: 'unspecified',
                secure: true,
                session: false,
                storeId: '0',
                value: 'OGylW0kPx6ZXoH9vVoFs09Gq3rLVQN5pKZwZIMLS',
                id: 13,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1722700984.167055,
                hostOnly: false,
                httpOnly: false,
                name: 'personalization_id',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: '"v1_QSKYC+VXfFaq1Uc05DLeJA=="',
                id: 14,
            },
            {
                domain: '.twitter.com',
                expirationDate: 1719676984.167068,
                hostOnly: false,
                httpOnly: false,
                name: 'twid',
                path: '/',
                sameSite: 'no_restriction',
                secure: true,
                session: false,
                storeId: '0',
                value: 'u%3D912747257694445570',
                id: 15,
            },
            {
                domain: 'twitter.com',
                expirationDate: 1693918873,
                hostOnly: true,
                httpOnly: false,
                name: 'g_state',
                path: '/',
                sameSite: 'unspecified',
                secure: false,
                session: false,
                storeId: '0',
                value: '{"i_l":0}',
                id: 16,
            },
            {
                domain: 'twitter.com',
                hostOnly: true,
                httpOnly: false,
                name: 'lang',
                path: '/',
                sameSite: 'unspecified',
                secure: false,
                session: true,
                storeId: '0',
                value: 'en',
                id: 17,
            },
        ],
        mode: 'own',
        profilesDesired: 1,
        proxyConfig: {
            useApifyProxy: true,
        },
        repliesDepth: 1,
        searchMode: 'live',
        skipRetweets: true,
        tweetsDesired: 2,
        useAdvancedSearch: false,
    })

    const { items }: any = await client.dataset(run.defaultDatasetId).listItems()

    return items
}
